# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-14 11:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_auto_20180414_0234'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabDirector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ResearchLab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_name', models.CharField(max_length=50)),
                ('lab_description', models.TextField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='labdirector',
            name='lab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.ResearchLab'),
        ),
    ]
