# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-16 01:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0003_auto_20180414_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='director',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='research.LabDirector'),
            preserve_default=False,
        ),
    ]
